Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using EFLib;
using EfLib.Repositories;
using Web.Interfaces;
using Web.Models;
using Web.Services;

namespace Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductViewModelService _productService;
        private readonly IRepository<Product> _productRepository;
        private readonly IRepository<Category> _categoryRepository;

        public ProductController(IRepository<Product> productRepository, IProductViewModelService productService,
            IRepository<Category> categoryRepository)
        {
            _productRepository = productRepository;
            _productService = productService;
            _categoryRepository = categoryRepository;
        }


        // GET: Product
        public IActionResult Index(int? categoryId)
        {
            var vm = _productService.GetProductsListVM(categoryId);
            return View(vm);
        }

        // GET: Product/Details/5
        public IActionResult Details(int id)
        {
            var product = _productRepository.GetById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            ProductVM model = new ProductVM();
            var categories = _categoryRepository.GetAll();
            model.ProductCategories = new List<ProductCategory>();
            model.Categories = GetCategoriesSelectList(categories, model);

            return View(model);
        }


        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(
            [Bind("Name, Description, Id, SelectedCategories")]
            ProductVM model)
        {
            if (ModelState.IsValid)
            {
                Product product = new Product()
                {
                    Name = model.Name,
                    Description = model.Description
                };

                product.ProductCategories = model.SelectedCategories.Select(i =>
                    new ProductCategory()
                    {
                        CategoryId = i,
                        ProductId = product.Id
                    }).ToList();

                _productRepository.Create(product);

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Product/Edit/5
        public IActionResult Edit(int id)
        {
            IReadOnlyList<Category> categories = _categoryRepository.GetAll();

            ProductVM model = _productService.GetProductVM(id);

            model.Categories = GetCategoriesSelectList(categories, model);

            return View(model);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,
            [Bind("Name,Description,Id,SelectedCategories")]
            ProductVM model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Product productInDb = _productRepository.GetById(id);

                productInDb.Name = model.Name;
                productInDb.Id = model.Id;
                productInDb.Description = model.Description;
                productInDb.ProductCategories = model.SelectedCategories.Select(
                    i => new ProductCategory()
                    {
                        CategoryId = i,
                        ProductId = model.Id
                    }).ToList();

                try
                {
                    _productRepository.Update(productInDb);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Product/Delete/5
        public IActionResult Delete(int id)
        {
            var product = _productRepository.GetById(id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var product = _productRepository.GetById(id);
            _productRepository.Delete(product);
            return RedirectToAction(nameof(Index));
        }

        private List<SelectListItem> GetCategoriesSelectList(
            IReadOnlyList<Category> categories,
            ProductVM model)
        {
            List<SelectListItem> selectList = new List<SelectListItem>();

            foreach (var category in categories)
            {
                bool selceted = false;
                SelectListGroup optionGroup = null;

                if (category.Children != null && category.Children.Count > 0)
                {
                    optionGroup = new SelectListGroup()
                    {
                        Name = category.Name
                    };
                    foreach (var ch in category.Children)
                    {
                        selectList.Add(new SelectListItem()
                        {
                            Text = ch.Name,
                            Value = ch.Id.ToString(),
                            Group = optionGroup,
                            Selected = ChekSelected(ch.Id,
                                model.ProductCategories)
                        });
                    }
                }
                else
                {
                    selectList.Add(new SelectListItem()
                    {
                        Text = category.Name,
                        Value = category.Id.ToString(),
                        Group = optionGroup,
                        Selected = ChekSelected(category.Id,
                            model.ProductCategories)
                    });
                }
            }

            return selectList;
        }

        private bool ChekSelected(int cId,
            ICollection<ProductCategory> categories)
        {
            return categories.Any(c => c.CategoryId == cId);
        }
    }
}

Web/Controllers/ProductImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using EFLib;
using EfLib.Repositories;

namespace Web.Controllers
{
    public class ProductImageController : Controller
    {
        private readonly IRepository<ProductImage> _imageRepository;
        public ProductImageController(IRepository<ProductImage> imageRepository)
        {
            _imageRepository = imageRepository;
        }


        // GET: ProductImage/Details/5
        public IActionResult Details(int id)
        {
            var img = _imageRepository.GetById(id);

            if (img == null)
            {
                return NotFound();
            }
            return View(img);
        }

        // GET: ProductImage/Create/productId
        public IActionResult Create(int productId)
        {

            return View();
        }

        // POST: ProductImage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Url,ProductId,Id")] ProductImage productImage)
        {
            if (ModelState.IsValid)
            {
                _imageRepository.Create(productImage);
                return RedirectToAction("Edit", "Product", new { id = productImage.ProductId });
            }
            return View(productImage);
        }

        // GET: ProductImage/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productImage = _imageRepository.GetById((int)id);
            if (productImage == null)
            {
                return NotFound();
            }

            return View(productImage);
        }

        // POST: ProductImage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Url,ProductId,Id")] ProductImage productImage)
        {
            if (id != productImage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _imageRepository.Update(productImage);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_imageRepository.IsOnlyOneEntity(productImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Edit", "Product", new { id = productImage.ProductId });
            }

            return View(productImage);
        }

        // GET: ProductImage/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productImage = _imageRepository.GetById((int)id);

            if (productImage == null)
            {
                return NotFound();
            }

            return View(productImage);
        }

        // POST: ProductImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {

            var img = _imageRepository.GetById(id);
            if (img != null)
            {
                _imageRepository.Delete(id);
            }

            return RedirectToAction("Edit", "Product", new { id = img.ProductId });
        }

    }
}

Web/Controllers/VarioationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using EFLib;
using EfLib.Repositories;

namespace Web.Controllers
{
    public class VarioationController : Controller
    {

        private readonly IRepository<Product> _productRepository;
        private readonly IRepository<ProductVarioation> _variationRepository;
        public VarioationController(IRepository<Product> productRepository, IRepository<ProductVarioation> variationRepository)
        {
            _productRepository = productRepository;
            _variationRepository = variationRepository;
        }


        // GET: Varioation/Details/5
        public IActionResult Details(int id)
        {

            var productVarioation = _variationRepository.GetById(id);
            if (productVarioation == null)
            {
                return NotFound();
            }

            return View(productVarioation);
        }

        // GET: Varioation/Create
        public IActionResult Create(int productId)
        {
            ViewData["ProductName"] = _productRepository.GetById(productId).Name;
            return View();
        }

        // POST: Varioation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Article,Price,ProductId,Description")] ProductVarioation productVarioation)
        {
            if (ModelState.IsValid)
            {
                _variationRepository.Create(productVarioation);

                return RedirectToAction("Edit", "Product", new { id = productVarioation.ProductId });
            }

            return View(productVarioation);
        }

        // GET: Varioation/Edit/5
        public IActionResult Edit(int id)
        {

            var productVarioation = _variationRepository.GetById(id);
            if (productVarioation == null)
            {
                return NotFound();
            }

            return View(productVarioation);
        }

        // POST: Varioation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Article,Price,ProductId,Description,Id")] ProductVarioation productVarioation)
        {
            if (id != productVarioation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _variationRepository.Update(productVarioation);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_variationRepository.IsOnlyOneEntity(productVarioation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Edit", "Product", new { id = productVarioation.ProductId });
            }

            return View(productVarioation);
        }

        // GET: Varioation/Delete/5
        public IActionResult Delete(int id)
        {
            var productVarioation = _variationRepository.GetById(id);
            if (productVarioation == null)
            {
                return NotFound();
            }

            return View(productVarioation);
        }

        // POST: Varioation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var productVarioation = _variationRepository.GetById(id);
            if (productVarioation != null)
            {
                _variationRepository.Delete(productVarioation);
            }

            return RedirectToAction("Edit", "Product", new { id = productVarioation.ProductId });
        }

    }
}

Web/Views/Product/Create.cshtml
@model Web.Models.ProductVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectedCategories"></label>
                <select asp-for="SelectedCategories" asp-items="@Model.Categories" class="custom-select w-100"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Product/Delete.cshtml
@model ApplicationCore.Entities.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web/Views/Product/Details.cshtml
@model ApplicationCore.Entities.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web/Views/Product/Edit.cshtml
@model Web.Models.ProductVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div class="productBlock">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="SelectedCategories"></label>
                    <select asp-for="SelectedCategories" asp-items="@Model.Categories" class="custom-select w-100"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
            <div class="ImagesBlock bg-light p-3">
                <h5>Product images  <a asp-action="Create" asp-controller="ProductImage" asp-route-productId="@Model.Id" class="btn btn-info float-right">Add image</a></h5>

                @if (Model.Images.Count > 0)
                {
                    <div class="row">
                        @foreach (var img in Model.Images)
                        {
                            <div class="card col-md-2" >
                            <img class="card-img-top" src="@img.Url"/>
                            <div class="card-body">
                                <a asp-action="Edit" asp-controller="ProductImage" asp-route-id="@img.Id" class="btn btn-primary">Edit</a>

                            </div>
                        </div>
                        }
                    </div>
                }

            </div>
            <div class="variationBlock p-3"> 
                <h5>Product variations  <a asp-action="Create" asp-controller="Varioation" asp-route-productId="@Model.Id" class="btn  btn-info float-right">Add variation</a></h5>

                @if (Model.Variations.Count > 0)
                {
                    <ul>
                        @foreach (var variation in Model.Variations)
                        {
                            <li><a asp-controller="Varioation" asp-action="Details" asp-route-id="@variation.Id">@variation.Article : @variation.Description </a></li>
                        }
                    </ul>
                }

            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Product/Index.cshtml
@model ProductIndexVM

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    <div class="col-md-3">
        <a asp-action="Index">All products</a>
        @await Component.InvokeAsync("CatalogNaviagation", new
        {
            categories = Model.Categories,
            isFirstCall = true
        })
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in Model.Products)
            {
                <div class="col-md-4">
                    <div class="card">
                        @{
                            var urlImg = "../images/no-product-image.png";
                            if (@product.Images.Count > 0)
                            {
                                urlImg = @product.Images.First().Url;
                            }
                           
                        }
                        <img class="card-img-top w-75 m-auto" src="@urlImg" alt="Card image cap" height="220">
                        <div class="card-body">
                            <span></span>
                            <h5 class="card-title">@product.Name</h5>
                            <p class="card-text">@product.Description</p>

                        </div>
                        @if (@product.Variations != null)
                        {
                            <ul class="list-group list-group-flush">
                                @foreach (var variation in @product.Variations)
                                {
                                    <li class="list-group-item">
                                        article: @variation.Article Цена: @variation.Price.ToString("0") rub <br/>
                                        <span>@variation.Description</span>
                                    </li>
                                }

                            </ul>
                        }
                        <div class="card-body">
                            Отзывы: @product.Comments.Count шт.
                        </div>
                        <div class="card-body">
                            <a asp-controller="Product" asp-action="Edit" asp-route-id="@product.Id" class="card-link">Edit</a>
                            <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id" class="card-link">Details</a>
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>
</div>